import json,os,collections,re
S=os.environ['S']
rs=[json.loads(l) for l in open(f'{S}/events.jsonl')]
rec=json.load(open(f'{S}/out_recon.json'))['report']
out=[];A=out.append
def tbl(counter,head):
    A(f'| {head} | count |'); A('| --- | ---: |')
    for k,v in sorted(counter.items(), key=lambda kv:(-kv[1],str(kv[0]))): A(f'| `{k}` | {v} |')
    A('')

A('# coverage.md')
A('')
A(f'`events.jsonl` holds **{len(rs)}** records. One JSON object per line. Sorted by lane,')
A('then by `timestamp_utc` inside the lane. `event_id` is `<lane>-NNNN`, sequential inside the lane.')
A('')
A('## What was read')
A('')
A('| source | branch | read at | what came out |')
A('| --- | --- | --- | --- |')
A('| `docs/runs/20260820T085531Z/run.md` | `run/local` | `89351d71` | machine log, tier `recorded` |')
A('| `docs/runs/20260820T102917Z/run.md` | `run/local` | `89351d71` | machine log, tier `recorded` |')
A('| `docs/runs/20260820T112543Z/run.md` | `run/local` | `89351d71` | machine log, tier `recorded` |')
A('| `docs/runs/<STAMP>/workers/*.log` (17 files) | `run/local` | `89351d71` | tier `derived` |')
A('| `docs/runs/<STAMP>/reviews/<slug>/` (16 dirs) | `run/local` | `89351d71` | tier `derived` |')
A('| commit metadata, 54 commits | `run/local` | `88400b80..89351d71` | tier `derived` |')
A('| commit metadata, 46 commits | `run/web` | `88400b80..9525e3e6` | tier `derived` |')
A('| `docs/runs/operator/local.md` | `chore/test-report-local` | tip `2f779a82` | F1-F36 + 25 phase rows, tier `reconstructed` |')
A('| `docs/runs/operator/web.md` | `chore/test-report-web` | tip `bfc25c1a` | 23 F headings + 131 table rows, tier `reconstructed` |')
A('| commit metadata, 17 commits | `chore/test-report-local` | `88400b80..2f779a82` | tier `derived` |')
A('| commit metadata, 44 commits | `chore/test-report-web` | `88400b80..bfc25c1a` | tier `derived` |')
A('| `docs/runs/operator/runner-2026-08-20.md` | `main` | `316ff10f` | RN-1..RN-3, tier `reconstructed` |')
A('| commit metadata, 4 commits | `main` | `88400b80..52735f8c` | tier `derived` |')
A('')
A('Excluded as instructed: commits `b443caa`, `eeeafab` and merge `5f0e372` on `run/local`')
A('(2026-08-24 post-experiment cleanup). `run/local` was read at `89351d71`, not at the tip.')
A('The GitHub API was not called. No commits, branches or pushes were made.')
A('')
A('## Per lane')
A('')
for lane in ['local','web','ledger-local','ledger-web','runner']:
    L=[r for r in rs if r['lane']==lane]
    A(f'### `{lane}` — {len(L)} events, {L[0]["timestamp_utc"]} to {L[-1]["timestamp_utc"]}')
    A('')
    A('**By `event_class`**'); A('')
    tbl(collections.Counter(r['event_class'] for r in L),'event_class')
    A('**By `phase`**'); A('')
    tbl(collections.Counter((r['phase'] or '(null)') for r in L),'phase')
    A('**By `evidence_tier`**'); A('')
    tbl(collections.Counter(r['evidence_tier'] for r in L),'evidence_tier')
    A('**By `timestamp_precision`**'); A('')
    tbl(collections.Counter(r['timestamp_precision'] for r in L),'timestamp_precision')
    A('**By `actor_role`**'); A('')
    tbl(collections.Counter(r['actor_role'] for r in L),'actor_role')
open(f'{S}/coverage_part1.md','w').write('\n'.join(out)+'\n')
print(len(out))
