import json,os,re,difflib
S=os.environ['S']
def num(n): return int(re.search(r'\d+',n).group())
esc=lambda s: s.replace('|','\\|')
out=[];A=out.append
A('# collision-check.md')
A('')
A('Mechanical diff of `docs/DESIGN.oracle.md` and `docs/BACKLOG.md` between the two lanes.')
A('')
A('- Left: `run/local` read at `89351d71b44fcc5382f2708cbeba6c2c905c7ae0` (the pinned commit, not the branch tip).')
A('- Right: `run/web` read at `9525e3e6be747c972d3e046a3f0a22367416274b` (branch tip).')
A('')
A('An id is reported when it is present on **both** branches and the text under it differs.')
A('**Nothing here is resolved.** Both texts are stated side by side; choosing between them is a later pass.')
A('')
A('Sectioning rule: a section starts at a line matching `#{1,6} <ID>` or `- **<ID>**`, and runs to the next such line.')
A('')
for f,fname in [('DESIGN.oracle','docs/DESIGN.oracle.md'),('BACKLOG','docs/BACKLOG.md')]:
    L=json.load(open(f'{S}/cmp/local-{f}.json'));W=json.load(open(f'{S}/cmp/web-{f}.json'))
    shared=sorted(set(L['secs'])&set(W['secs']),key=num)
    diff=[i for i in shared if L['secs'][i].strip()!=W['secs'][i].strip()]
    same=[i for i in shared if i not in diff]
    A(f'## `{fname}`')
    A('')
    A(f'- ids present on both branches: **{len(shared)}**')
    A(f'- text differs: **{len(diff)}** — {", ".join(diff)}')
    A(f'- text identical: **{len(same)}** — {", ".join(same)}')
    A(f'- `run/local` only: {", ".join(sorted(set(L["secs"])-set(W["secs"]),key=num)) or "(none)"}')
    A(f'- `run/web` only: {", ".join(sorted(set(W["secs"])-set(L["secs"]),key=num)) or "(none)"}')
    A('')
    for i in diff:
        lh,wh=L['heads'][i],W['heads'][i]
        ls,ws=L['secs'][i],W['secs'][i]
        A(f'### {i}')
        A('')
        A('| lane | headline as written | lines | bytes |')
        A('| --- | --- | ---: | ---: |')
        A('| `run/local` | '+esc(lh)+f' | {len(ls.splitlines())} | {len(ls.encode())} |')
        A('| `run/web` | '+esc(wh)+f' | {len(ws.splitlines())} | {len(ws.encode())} |')
        A('')
        if lh==wh:
            A('Headlines are byte-identical; the section bodies differ. Full unified diff:')
            A('')
            A('```diff')
            for r in list(difflib.unified_diff(ls.splitlines(),ws.splitlines(),
                          'run/local','run/web',lineterm='',n=1))[:80]: A(r)
            A('```')
            A('')
            if i=='BL-13':
                A('Note, factual: every added line is the document section heading')
                A('`## Uncertainties awaiting oracle ruling` and its explanatory italics, which follow')
                A('BL-13 on `run/web` and carry no id of their own, so the sectioning rule above')
                A('attributes them to BL-13. BL-13\'s own prose is identical on both branches.')
                A('Reported because the rule produced a difference. Not resolved.')
                A('')
        else:
            A('**Headlines disagree: the two lanes gave this id to different subjects.**')
            A('')
            A('Opening of each side, verbatim (list-form entries wrap, so one line is not the whole headline):')
            A('')
            A('```')
            A('run/local:')
            for r in [x for x in ls.splitlines() if x.strip()][:4]: A('  '+r)
            A('')
            A('run/web:')
            for r in [x for x in ws.splitlines() if x.strip()][:4]: A('  '+r)
            A('```')
            A('')
A('## Not compared')
A('')
A('- `docs/DESIGN.md`, `docs/VISION.md`, `docs/DECISIONS.md` — outside the two files this pass was asked to diff.')
A('- Requirement ids (`R…`), vision ids (`V…`) and scope ids (`S…`) are not separately sectioned in either file, so they are not diffed here as ids. They appear in `ids_referenced` on the events that touch them.')
A('- `F` ids: the two operator ledgers live on different branches and are not the subject of this diff. Their id collision is recorded in `coverage.md`.')
open(f'{S}/collision-check.md','w').write('\n'.join(out)+'\n')
print(len(out),'lines')
