# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.4.27
_src_path: git+https://github.com/GrimsVerk/grimsverk-template.git
auto_merge: true
code_owner: '@GrimsVerk'
description: Searching Buildzoid videos on YT to extract his top pick for an AMD mobo.
language: python
project_name: find-best-mobo
